"""note expired

Revision ID: defd729a351b
Revises: 43aec85d9386
Create Date: 2023-09-10 21:56:21.238485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'defd729a351b'
down_revision = '43aec85d9386'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_column('expired')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expired', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
